#cloud-config
users:
  - name: ${username}
    ssh-authorized-keys:
      - ${ssh_public_key}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash

package_update: true

packages: ${packages}

runcmd:
  - curl -s https://install.terraform.io/ptfe/stable | bash -s local-address=${ip_address} public-address=${ip_address} no-proxy
